Repository Dreaming-Star/space-star-back-member, pull requests merged in 2024-06, with the labels that each got.

#16 Feat: 회원 탈퇴
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/member/controller/MemberController.java
  src/main/java/com/spacestar/back/member/domain/Member.java
  src/main/java/com/spacestar/back/member/repository/MemberRepository.java
  src/main/java/com/spacestar/back/member/repository/ProfileImageRepository.java
  src/main/java/com/spacestar/back/member/service/AuthServiceImp.java
  src/main/java/com/spacestar/back/member/service/MemberService.java
  src/main/java/com/spacestar/back/member/service/MemberServiceImp.java
Labels: 📬 API, ✨ Feature

#24 Feat: 프로필 수정 및 조회
  src/main/java/com/spacestar/back/global/ResponseStatus.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/domain/LikedGame.java
  src/main/java/com/spacestar/back/profile/domain/PlayGame.java
  src/main/java/com/spacestar/back/profile/domain/Profile.java
  src/main/java/com/spacestar/back/profile/domain/ProfileImage.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileInfoReqDto.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfilePlayGameInfoReqDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileInfoResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileLikedGameResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfilePlayGameInfoResDto.java
  src/main/java/com/spacestar/back/profile/repository/LikedGameRepository.java
  src/main/java/com/spacestar/back/profile/repository/PlayGameRepository.java
  src/main/java/com/spacestar/back/profile/repository/ProfileRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/req/ProfileInfoReqVo.java
  src/main/java/com/spacestar/back/profile/vo/req/ProfilePlayGameInfoReqVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileInfoResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileLikedGameResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfilePlayGameInfoResVo.java
Labels: 📬 API, ✨ Feature

#25 Feat: 프로필 사진 조회
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/domain/ProfileImage.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileImageReqDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileImageListResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileMainImageResDto.java
  src/main/java/com/spacestar/back/profile/repository/ProfileImageRepository.java
  src/main/java/com/spacestar/back/profile/repository/ProfileRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/req/ProfileImageReqVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileImageListResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileMainImageResVo.java
Labels: 📬 API, ✨ Feature

#27 Refactor : 로그인 시 프로필 존재 유무 확인
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/domain/Profile.java
  src/main/java/com/spacestar/back/profile/domain/ProfileImage.java
  src/main/java/com/spacestar/back/profile/dto/req/KakaoProfileImageReqDto.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileImageReqDto.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileInfoReqDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileExistResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileInfoResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileSwipeResDto.java
  src/main/java/com/spacestar/back/profile/repository/LikedGameRepository.java
  src/main/java/com/spacestar/back/profile/repository/PlayGameRepository.java
  src/main/java/com/spacestar/back/profile/repository/ProfileImageRepository.java
  src/main/java/com/spacestar/back/profile/repository/ProfileRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/req/KakaoProfileImageReqVo.java
  src/main/java/com/spacestar/back/profile/vo/req/ProfileInfoReqVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileExistResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileInfoResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileSwipeResVo.java
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#31 Feat: 친구 기능
  src/main/java/com/spacestar/back/friend/controller/FreindController.java
  src/main/java/com/spacestar/back/friend/domain/Friend.java
  src/main/java/com/spacestar/back/friend/dto/req/FriendUuidReqDto.java
  src/main/java/com/spacestar/back/friend/dto/res/FriendListResDto.java
  src/main/java/com/spacestar/back/friend/dto/res/FriendRequestResDto.java
  src/main/java/com/spacestar/back/friend/enums/FriendType.java
  src/main/java/com/spacestar/back/friend/repository/FriendRepository.java
  src/main/java/com/spacestar/back/friend/service/FriendService.java
  src/main/java/com/spacestar/back/friend/service/FriendServiceImp.java
  src/main/java/com/spacestar/back/friend/vo/req/FriendUuidReqVo.java
  src/main/java/com/spacestar/back/friend/vo/res/FriendListResVo.java
  src/main/java/com/spacestar/back/friend/vo/res/FriendRequestResVo.java
  src/main/java/com/spacestar/back/global/ResponseStatus.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
Labels: 📬 API, ✨ Feature

#36 Feat: 차단 기능
  src/main/java/com/spacestar/back/block/controller/BlockController.java
  src/main/java/com/spacestar/back/block/domain/Block.java
  src/main/java/com/spacestar/back/block/dto/req/BlockReqDto.java
  src/main/java/com/spacestar/back/block/dto/res/BlockExistResDto.java
  src/main/java/com/spacestar/back/block/dto/res/BlockListResDto.java
  src/main/java/com/spacestar/back/block/repository/BlockRepository.java
  src/main/java/com/spacestar/back/block/service/BlockService.java
  src/main/java/com/spacestar/back/block/service/BlockServiceImp.java
  src/main/java/com/spacestar/back/block/vo/req/BlockReqVo.java
  src/main/java/com/spacestar/back/block/vo/res/BlockExistResVo.java
  src/main/java/com/spacestar/back/block/vo/res/BlockListResVo.java
  src/main/java/com/spacestar/back/friend/controller/FreindController.java
  src/main/java/com/spacestar/back/friend/dto/res/IsFriendResDto.java
  src/main/java/com/spacestar/back/friend/repository/FriendRepository.java
  src/main/java/com/spacestar/back/friend/service/FriendService.java
  src/main/java/com/spacestar/back/friend/service/FriendServiceImp.java
  src/main/java/com/spacestar/back/friend/vo/req/IsFriendResVo.java
  src/main/java/com/spacestar/back/global/ResponseStatus.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/dto/req/KakaoProfileImageReqDto.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileImageReqDto.java
  src/main/java/com/spacestar/back/profile/repository/ProfileImageRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/req/KakaoProfileImageReqVo.java
Labels: 📬 API, ✨ Feature

#37 Feat : 신고기능
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/repository/ProfileRepository.java
  src/main/java/com/spacestar/back/report/controller/ReportController.java
  src/main/java/com/spacestar/back/report/converter/ReportConverter.java
  src/main/java/com/spacestar/back/report/domain/Report.java
  src/main/java/com/spacestar/back/report/dto/req/ReportReqDto.java
  src/main/java/com/spacestar/back/report/repository/ReportRepository.java
  src/main/java/com/spacestar/back/report/service/ReportService.java
  src/main/java/com/spacestar/back/report/service/ReportServiceImpl.java
  src/main/java/com/spacestar/back/report/vo/req/ReportReqVo.java
Labels: 📬 API, ✨ Feature

#43 feat: quick-matching profile select
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/dto/res/QuickMemberInfoResDto.java
  src/main/java/com/spacestar/back/profile/repository/PlayGameRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/res/QuickMemberInfoResVo.java
Labels: 📬 API, ✨ Feature

#46 Refactor: kafka 적용
  build.gradle
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/kafka/ProfileDto.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/domain/Profile.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileExistResDto.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileExistResVo.java
Labels: 🔨 Refactor

#48 feat: 대표 게임 조회
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/dto/res/MainGameResDto.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/res/MainGameResVo.java
Labels: 📬 API, ✨ Feature

#50 refactor: 이름 통일 및 VO 값 수정
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/dto/req/ProfileInfoReqDto.java
  src/main/java/com/spacestar/back/profile/dto/res/MainGameResDto.java
  src/main/java/com/spacestar/back/profile/dto/res/ProfileInfoResDto.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/req/ProfileInfoReqVo.java
  src/main/java/com/spacestar/back/profile/vo/res/MainGameResVo.java
  src/main/java/com/spacestar/back/profile/vo/res/ProfileInfoResVo.java
Labels: 🔨 Refactor

#52 feat: 친구 상호 상태 확인
  src/main/java/com/spacestar/back/friend/controller/FreindController.java
  src/main/java/com/spacestar/back/friend/dto/res/FriendNowResDto.java
  src/main/java/com/spacestar/back/friend/enums/FriendNowType.java
  src/main/java/com/spacestar/back/friend/service/FriendService.java
  src/main/java/com/spacestar/back/friend/service/FriendServiceImp.java
  src/main/java/com/spacestar/back/friend/vo/res/FriendNowResVo.java
  src/main/java/com/spacestar/back/global/ResponseSuccess.java
Labels: 📬 API, ✨ Feature

#56 Feat: 친구 요청 혹은 수락 시 알림으로 uuid 전송
  src/main/java/com/spacestar/back/friend/service/FriendServiceImp.java
  src/main/java/com/spacestar/back/kafka/FriendMessage.java
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#54 Feat : 스와이프에서 필요한 사용자 정보 조회
  build.gradle
  src/main/java/com/spacestar/back/config/QueryDslConfig.java
  src/main/java/com/spacestar/back/profile/controller/ProfileController.java
  src/main/java/com/spacestar/back/profile/dto/res/SwipeMemberInfoResDto.java
  src/main/java/com/spacestar/back/profile/repository/CustomProfileRepository.java
  src/main/java/com/spacestar/back/profile/repository/CustomProfileRepositoryImpl.java
  src/main/java/com/spacestar/back/profile/repository/ProfileRepository.java
  src/main/java/com/spacestar/back/profile/service/ProfileService.java
  src/main/java/com/spacestar/back/profile/service/ProfileServiceImp.java
  src/main/java/com/spacestar/back/profile/vo/res/SwipeMemberInfoResVo.java
Labels: 📬 API, ✨ Feature
